USE [TN_CSDLPT]
GO

/****** Object:  UserDefinedFunction [dbo].[FN_KTDaThi]    Script Date: 12/21/2020 11:09:16 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


ALTER FUNCTION [dbo].[FN_KTDaThi] (@MAMH NCHAR(8), @MALOP nchar(5), @LAN smallint)
RETURNS NCHAR(2)
AS
BEGIN
	DECLARE @CHECKED NCHAR(1)
	SET @CHECKED = ' '
	IF EXISTS(
	SELECT * 
	FROM dbo.BANGDIEM
	WHERE MAMH = @MAMH AND LAN = @LAN AND MASV IN(SELECT MASV FROM SINHVIEN WHERE MALOP = @MALOP))
	BEGIN
		SET @CHECKED = 'X'
		RETURN @CHECKED
	END
	RETURN @CHECKED
END

GO

