USE [TN_CSDLPT]
GO

/****** Object:  StoredProcedure [dbo].[SP_CHUANBITHI]    Script Date: 12/5/2020 11:49:50 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SP_CHUANBITHI] (@MAMH NCHAR(5), @TRINHDO NCHAR(1), @SOCAUTHI INT)
AS
BEGIN
	DECLARE @TRINHDO_THAP NCHAR(1), @DEM1 INT, @DEM2 INT, @DEM3 INT, @DEM4 INT, @ErorStr nvarchar(200)

	IF @TRINHDO = 'A'
	BEGIN
		SET @TRINHDO_THAP = 'B'
	END
	IF @TRINHDO = 'B'
	BEGIN
		SET @TRINHDO_THAP = 'C'
	END

	IF @TRINHDO = 'A' OR @TRINHDO = 'B' --  VI DUOI TRINH DO C KHONG CO TRINH DO NAO NUA NEN XET TRUONG HOP RIENG
	BEGIN
		SET @DEM1 = (SELECT COUNT(*) FROM dbo.BODE WHERE MAMH = @MAMH AND TRINHDO = @TRINHDO AND MAGV IN (SELECT MAGV FROM dbo.GIAOVIEN WHERE MAKH IN (SELECT MAKH FROM dbo.KHOA)))
		IF @DEM1 >= @SOCAUTHI -- DU CAU THI
		BEGIN
			--RAISERROR('YES', 16, 1)
			RETURN
		END
		ELSE IF @DEM1 >= (@SOCAUTHI*0.7) -- BEN CS1 %CAU TDA >= 70%, LAY THEM CAU TDB
		BEGIN
			SET @DEM2 = (SELECT COUNT(*) FROM dbo.BODE WHERE MAMH = @MAMH AND TRINHDO = @TRINHDO_THAP AND MAGV IN (SELECT MAGV FROM dbo.GIAOVIEN WHERE MAKH IN (SELECT MAKH FROM dbo.KHOA)))
			IF @DEM2 >= (@SOCAUTHI - @DEM1) -- DU CAU THI
			BEGIN
				--RAISERROR('YES', 16, 1)
				RETURN
			END
			ELSE -- QUA BEN CS2 LAY THEM CAU TDA
			BEGIN
				SET @DEM3 = (SELECT COUNT(*) FROM dbo.BODE WHERE MAMH = @MAMH AND TRINHDO = @TRINHDO AND MAGV IN (SELECT MAGV FROM dbo.GIAOVIEN WHERE MAKH NOT IN (SELECT MAKH FROM dbo.KHOA)))
				IF @DEM3 >= (@SOCAUTHI - @DEM1 - @DEM2) -- DU CAU THI
				BEGIN
					--RAISERROR('YES', 16, 1)
					RETURN
				END
				ELSE -- SO CAU TDA BEN CS2 CHUA DU LAY THEM CAU TDB
				BEGIN
					SET @DEM4 = (SELECT COUNT(*) FROM dbo.BODE WHERE MAMH = @MAMH AND TRINHDO = @TRINHDO_THAP AND MAGV IN (SELECT MAGV FROM dbo.GIAOVIEN WHERE MAKH NOT IN (SELECT MAKH FROM dbo.KHOA)))
					IF @DEM4 >= (@SOCAUTHI - @DEM1 - @DEM2 - @DEM3) -- DU CAU THI
					BEGIN
						--RAISERROR('YES', 16, 1)
						RETURN
					END
					ELSE -- KHONG DU CAU THI, BAO LOI
					BEGIN
						SET @ErorStr = N'Thiếu câu hỏi thi! Thiếu "'+ rtrim(convert(nvarchar(200),@SoCauThi - (@DEM1 + @DEM2 + @DEM3 + @DEM4))) +N'" câu hỏi, cần thêm câu hỏi vào trình độ hiện tại (hoặc thấp hơn 1 bậc)!' 
						RAISERROR(@ErorStr, 16, 1)
						RETURN
					END
				END
			END
		END
		ELSE -- BEN CS1 %CAU TDA < 70%, LAY THEM CAU TDA BEN CS2
		BEGIN
			SET @DEM2 = (SELECT COUNT(*) FROM dbo.BODE WHERE MAMH = @MAMH AND TRINHDO = @TRINHDO AND MAGV IN (SELECT MAGV FROM dbo.GIAOVIEN WHERE MAKH NOT IN (SELECT MAKH FROM dbo.KHOA)))
			IF @DEM2 >= (@SOCAUTHI - @DEM1) -- DU CAU THI
			BEGIN
				--RAISERROR('YES', 16, 1)
				RETURN
			END
			ELSE IF @DEM2 >= (@SOCAUTHI*0.7 - @DEM1) -- %CAU TDA (CS1 + CS2) >= 70%, LAY CAU TDB BEN CS1 THEM
			BEGIN
				SET @DEM3 = (SELECT COUNT(*) FROM dbo.BODE WHERE MAMH = @MAMH AND TRINHDO = @TRINHDO_THAP AND MAGV IN (SELECT MAGV FROM dbo.GIAOVIEN WHERE MAKH IN (SELECT MAKH FROM dbo.KHOA)))
				IF @DEM3 >= (@SOCAUTHI - @DEM1 - @DEM2) -- DU CAU THI
				BEGIN
					--RAISERROR('YES', 16, 1)
					RETURN
				END
				ELSE -- CAU TDB BEN CS1 CHUA DU, LAY THEM CAU TDB BEN CS2
				BEGIN
					SET @DEM4 = (SELECT COUNT(*) FROM dbo.BODE WHERE MAMH = @MAMH AND TRINHDO = @TRINHDO_THAP AND MAGV IN (SELECT MAGV FROM dbo.GIAOVIEN WHERE MAKH NOT IN (SELECT MAKH FROM dbo.KHOA)))
					IF @DEM4 >= (@SOCAUTHI - @DEM1 - @DEM2 - @DEM3) -- DU CAU THI
					BEGIN
						--RAISERROR('YES', 16, 1)
						RETURN
					END
					ELSE -- KHONG DU CAU THI, BAO LOI
					BEGIN
						SET @ErorStr = N'Thiếu câu hỏi thi! Thiếu "'+ rtrim(convert(nvarchar(200),@SoCauThi - (@DEM1 + @DEM2 + @DEM3 + @DEM4))) +N'" câu hỏi, cần thêm câu hỏi vào trình độ hiện tại (hoặc thấp hơn 1 bậc)!' 
						RAISERROR(@ErorStr, 16, 1)
						RETURN
					END
				END
			END
			ELSE -- %CAU TDA (CS1 + CS2) < 70% => KHONG DU CAU THI, BAO LOI
			BEGIN
				SET @ErorStr = N'Thiếu câu hỏi thi! Thiếu "'+ rtrim(convert(nvarchar(200),FLOOR(@SoCauThi*0.7) - (@DEM1 + @DEM2))) +N'" câu hỏi cùng trình độ để đủ chỉ tiêu ít nhất 70 phần trăm câu hỏi cùng trình độ!' 
				RAISERROR(@ErorStr, 16, 1)
				RETURN
			END
		END
	END
	ELSE -- TRINH DO C
	BEGIN
		SET @DEM1 = (SELECT COUNT(*) FROM dbo.BODE WHERE MAMH = @MAMH AND TRINHDO = @TRINHDO AND MAGV IN (SELECT MAGV FROM dbo.GIAOVIEN WHERE MAKH IN (SELECT MAKH FROM dbo.KHOA)))
		IF @DEM1 >= @SOCAUTHI -- DU CAU THI
		BEGIN
			--RAISERROR('YES', 16, 1)
			RETURN
		END
		ELSE  -- BEN CS1 CHUA DU CAU THI
		BEGIN
			SET @DEM2 = (SELECT COUNT(*) FROM dbo.BODE WHERE MAMH = @MAMH AND TRINHDO = @TRINHDO AND MAGV IN (SELECT MAGV FROM dbo.GIAOVIEN WHERE MAKH NOT IN (SELECT MAKH FROM dbo.KHOA)))
			IF @DEM2 >= @SOCAUTHI - @DEM1 -- BEN CS2 + CS1 DU CAU THI
			BEGIN
				--RAISERROR('YES', 16, 1)
				RETURN
			END
			ELSE -- KHONG DU CAU THI, BAO LOI
			BEGIN
				SET @ErorStr = N'Thiếu câu hỏi thi! Thiếu "'+ rtrim(convert(nvarchar(200),@SoCauThi - (@DEM1 + @DEM2))) +N'" câu hỏi cùng trình độ !' 
				RAISERROR(@ErorStr, 16, 1)
				RETURN
			END
		END
	END
END
GO

