USE [TN_CSDLPT]
GO

/****** Object:  StoredProcedure [dbo].[SP_DSDKThi]    Script Date: 12/22/2020 13:28:07 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [dbo].[SP_DSDKThi]
	@NGAY1 DATETIME,
	@NGAY2 DATETIME
AS
BEGIN
	DECLARE @Table TABLE(MALOP NCHAR(8), MAMH NCHAR(5), MAGV NCHAR(8), SOCAUTHI INT, NGAYTHI DATETIME ,DATHI NCHAR(1))

	INSERT INTO @Table SELECT MALOP, MAMH, MAGV, SOCAUTHI, NGAYTHI ,[dbo].[FN_KTDaThi](GIAOVIEN_DANGKY.MAMH, GIAOVIEN_DANGKY.MALOP, LAN) AS DATHI
	FROM dbo.GIAOVIEN_DANGKY
	WHERE NGAYTHI BETWEEN @NGAY1 AND @NGAY2

	SELECT TENLOP, TENMH, HO + ' ' + TEN AS HOTEN, SOCAUTHI, NGAYTHI, DATHI
	FROM @Table JOIN dbo.LOP ON LOP.MALOP = [@Table].MALOP
	JOIN dbo.MONHOC ON MONHOC.MAMH = [@Table].MAMH
	JOIN dbo.GIAOVIEN ON GIAOVIEN.MAGV = [@Table].MAGV
	ORDER BY NGAYTHI
END



GO

