USE [TN_CSDLPT]
GO

/****** Object:  StoredProcedure [dbo].[SP_KTBangDiemNULL]    Script Date: 12/15/2020 17:17:28 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SP_KTBangDiemNULL]
	@MAMH NCHAR(5),
	@LAN SMALLINT,
	@MALOP NCHAR(8)
AS
BEGIN
	IF EXISTS(
		SELECT SINHVIEN.MASV, HO, TEN, DIEM
		FROM dbo.SINHVIEN JOIN dbo.BANGDIEM
		ON BANGDIEM.MASV = SINHVIEN.MASV
		WHERE BANGDIEM.MAMH = @MAMH AND BANGDIEM.LAN = @LAN AND SINHVIEN.MALOP = @MALOP
	)
	BEGIN
		RETURN 1
	END
	ELSE
		RAISERROR('Chưa có bảng điểm môn này!', 16, 1)
END
GO

