USE [TN_CSDLPT]
GO

/****** Object:  StoredProcedure [dbo].[SP_KTDATHI]    Script Date: 12/21/2020 11:13:44 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


ALTER PROCEDURE [dbo].[SP_KTDATHI] (@MASV NCHAR(8), @MAMH NCHAR(5), @LAN INT)
AS
BEGIN
	IF EXISTS(SELECT * FROM dbo.BANGDIEM WHERE MAMH = @MAMH AND MASV = @MASV AND LAN = @LAN)
		RAISERROR ('Lỗi! Môn này đã thi!', 16, 1)
	ELSE
		RETURN 1
END

GO

