USE [TN_CSDLPT]
GO

/****** Object:  StoredProcedure [dbo].[SP_THI]    Script Date: 11/30/2020 8:57:27 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SP_THI] (@MAMH CHAR(5), @TRINHDO CHAR(1), @SOCAUTHI SMALLINT)
AS
BEGIN
	DECLARE @TRINHDO_THAP NCHAR(1), @DEM1 INT, @DEM2 INT, @DEM3 INT, @DEM4 INT, @ErorStr nvarchar(200)

	CREATE TABLE #TAM (
		CAUHOI INT,
		MAMH CHAR(5),
		TRINHDO CHAR(1),
		NOIDUNG NVARCHAR(500),
		A NVARCHAR(100),
		B NVARCHAR(100),
		C NVARCHAR(100),
		D NVARCHAR(100),
		DAP_AN CHAR(1),
		MAGV CHAR(8)
	);

	IF @TRINHDO = 'A'
	BEGIN
		SET @TRINHDO_THAP = 'B'
	END
	IF @TRINHDO = 'B'
	BEGIN
		SET @TRINHDO_THAP = 'C'
	END

	IF @TRINHDO = 'A' OR @TRINHDO = 'B' --  VI DUOI TRINH DO C KHONG CO TRINH DO NAO NUA NEN XET TRUONG HOP RIENG
	BEGIN
		SET @DEM1 = (SELECT COUNT(*) FROM dbo.BODE WHERE MAMH = @MAMH AND TRINHDO = @TRINHDO AND MAGV IN (SELECT MAGV FROM dbo.GIAOVIEN WHERE MAKH IN (SELECT MAKH FROM dbo.KHOA)))
		IF @DEM1 >= @SOCAUTHI -- DU CAU THI
		BEGIN
			--RAISERROR('YES', 16, 1)
			--DEM1 >= 100%
			INSERT INTO #TAM SELECT TOP (@SOCAUTHI) CAUHOI, MAMH, TRINHDO, NOIDUNG, A, B, C, D, DAP_AN, MAGV FROM BODE  WHERE TRINHDO = @TRINHDO AND MAMH = @MAMH AND MAGV IN (SELECT MAGV FROM GIAOVIEN WHERE MAKH IN (SELECT MAKH FROM KHOA)) ORDER BY NEWID()
		END
		ELSE IF @DEM1 >= FLOOR(@SOCAUTHI*0.7) -- BEN CS1 %CAU TDA >= 70%, LAY THEM CAU TDB
		BEGIN
			--LAY HET DEM1 ( 100% > DEM1 >= 70% )
			INSERT INTO #TAM SELECT TOP (@DEM1) CAUHOI, MAMH, TRINHDO, NOIDUNG, A, B, C, D, DAP_AN, MAGV FROM dbo.BODE WHERE TRINHDO = @TRINHDO AND MAMH = @MAMH AND MAGV IN (SELECT MAGV FROM GIAOVIEN WHERE MAKH IN (SELECT MAKH FROM KHOA)) ORDER BY NEWID()
			
			SET @DEM2 = (SELECT COUNT(*) FROM dbo.BODE WHERE MAMH = @MAMH AND TRINHDO = @TRINHDO_THAP AND MAGV IN (SELECT MAGV FROM dbo.GIAOVIEN WHERE MAKH IN (SELECT MAKH FROM dbo.KHOA)))
			IF @DEM2 >= (@SOCAUTHI - @DEM1) -- DU CAU THI
			BEGIN
				--RAISERROR('YES', 16, 1)
				--DA CO DEM1, DEM1+DEM2 >= 100%, LAY VUA DU DEM2
				INSERT INTO #TAM SELECT TOP (@SOCAUTHI - @DEM1) CAUHOI, MAMH, TRINHDO, NOIDUNG, A, B, C, D, DAP_AN, MAGV FROM dbo.BODE WHERE TRINHDO = @TRINHDO_THAP AND MAMH = @MAMH AND MAGV IN (SELECT MAGV FROM GIAOVIEN WHERE MAKH IN (SELECT MAKH FROM KHOA)) ORDER BY NEWID()
			END
			ELSE -- QUA BEN CS2 LAY THEM CAU TDA
			BEGIN
				--DA CO DEM1, LAY HET DEM2
				INSERT INTO #TAM SELECT TOP (@DEM2) CAUHOI, MAMH, TRINHDO, NOIDUNG, A, B, C, D, DAP_AN, MAGV FROM dbo.BODE WHERE TRINHDO = @TRINHDO_THAP AND MAMH = @MAMH AND MAGV IN (SELECT MAGV FROM GIAOVIEN WHERE MAKH IN (SELECT MAKH FROM KHOA)) ORDER BY NEWID()
				 
				SET @DEM3 = (SELECT COUNT(*) FROM dbo.BODE WHERE MAMH = @MAMH AND TRINHDO = @TRINHDO AND MAGV IN (SELECT MAGV FROM dbo.GIAOVIEN WHERE MAKH NOT IN (SELECT MAKH FROM dbo.KHOA)))
				IF @DEM3 >= (@SOCAUTHI - @DEM1 - @DEM2) -- DU CAU THI
				BEGIN
					--RAISERROR('YES', 16, 1)
					--DA CO DEM1, DEM2, LAY VUA DU DEM3
					INSERT INTO #TAM SELECT TOP (@SOCAUTHI - @DEM1 - @DEM2) CAUHOI, MAMH, TRINHDO, NOIDUNG, A, B, C, D, DAP_AN, MAGV FROM dbo.BODE WHERE TRINHDO = @TRINHDO AND MAMH = @MAMH AND MAGV IN (SELECT MAGV FROM GIAOVIEN WHERE MAKH NOT IN (SELECT MAKH FROM KHOA)) ORDER BY NEWID()
				END
				ELSE -- SO CAU TDA BEN CS2 CHUA DU LAY THEM CAU TDB
				BEGIN
					--DA CO DEM1, DEM2, LAY HET DEM3
					INSERT INTO #TAM SELECT TOP (@DEM3) CAUHOI, MAMH, TRINHDO, NOIDUNG, A, B, C, D, DAP_AN, MAGV FROM dbo.BODE WHERE TRINHDO = @TRINHDO AND MAMH = @MAMH AND MAGV IN (SELECT MAGV FROM GIAOVIEN WHERE MAKH NOT IN (SELECT MAKH FROM KHOA)) ORDER BY NEWID()

					SET @DEM4 = (SELECT COUNT(*) FROM dbo.BODE WHERE MAMH = @MAMH AND TRINHDO = @TRINHDO_THAP AND MAGV IN (SELECT MAGV FROM dbo.GIAOVIEN WHERE MAKH NOT IN (SELECT MAKH FROM dbo.KHOA)))
					IF @DEM4 >= (@SOCAUTHI - @DEM1 - @DEM2 - @DEM3) -- DU CAU THI
					BEGIN
						--RAISERROR('YES', 16, 1)
						--DA CO DEM1, DEM2, DEM3, LAY VUA DU DEM4
						INSERT INTO #TAM SELECT TOP (@SOCAUTHI - @DEM1 - @DEM2 - @DEM3) CAUHOI, MAMH, TRINHDO, NOIDUNG, A, B, C, D, DAP_AN, MAGV FROM dbo.BODE WHERE TRINHDO = @TRINHDO_THAP AND MAMH = @MAMH AND MAGV IN (SELECT MAGV FROM GIAOVIEN WHERE MAKH NOT IN (SELECT MAKH FROM KHOA)) ORDER BY NEWID()
					END
					ELSE -- KHONG DU CAU THI, BAO LOI
					BEGIN
						SET @ErorStr = N'Thiếu câu hỏi thi! Thiếu "'+ rtrim(convert(nvarchar(200),@SoCauThi - (@DEM1 + @DEM2 + @DEM3 + @DEM4))) +N'" câu hỏi, cần thêm câu hỏi vào trình độ hiện tại (hoặc thấp hơn 1 bậc)!' 
						RAISERROR(@ErorStr, 16, 1)
						RETURN
					END
				END
			END
		END
		ELSE -- BEN CS1 %CAU TDA < 70%, LAY THEM CAU TDA BEN CS2
		BEGIN
			--LAY HET DEM1
			INSERT INTO #TAM SELECT TOP (@DEM1) CAUHOI, MAMH, TRINHDO, NOIDUNG, A, B, C, D, DAP_AN, MAGV FROM dbo.BODE WHERE TRINHDO = @TRINHDO AND MAMH = @MAMH AND MAGV IN (SELECT MAGV FROM GIAOVIEN WHERE MAKH IN (SELECT MAKH FROM KHOA)) ORDER BY NEWID()

			SET @DEM2 = (SELECT COUNT(*) FROM dbo.BODE WHERE MAMH = @MAMH AND TRINHDO = @TRINHDO AND MAGV IN (SELECT MAGV FROM dbo.GIAOVIEN WHERE MAKH NOT IN (SELECT MAKH FROM dbo.KHOA)))
			IF @DEM2 >= (@SOCAUTHI - @DEM1) -- DU CAU THI
			BEGIN
				--RAISERROR('YES', 16, 1)
				--DA CO DEM1, LAY VUA DU DEM2
				INSERT INTO #TAM SELECT TOP (@SOCAUTHI - @DEM1) CAUHOI, MAMH, TRINHDO, NOIDUNG, A, B, C, D, DAP_AN, MAGV FROM dbo.BODE WHERE TRINHDO = @TRINHDO AND MAMH = @MAMH AND MAGV IN (SELECT MAGV FROM GIAOVIEN WHERE MAKH NOT IN (SELECT MAKH FROM KHOA)) ORDER BY NEWID()
			END
			ELSE IF @DEM2 >= (FLOOR(@SOCAUTHI*0.7) - @DEM1) -- %CAU TDA (CS1 + CS2) >= 70%, LAY CAU TDB BEN CS1 THEM
			BEGIN
				--DA CO DEM1, LAY HET DEM2
				INSERT INTO #TAM SELECT TOP (@DEM2) CAUHOI, MAMH, TRINHDO, NOIDUNG, A, B, C, D, DAP_AN, MAGV FROM dbo.BODE WHERE TRINHDO = @TRINHDO AND MAMH = @MAMH AND MAGV IN (SELECT MAGV FROM GIAOVIEN WHERE MAKH NOT IN (SELECT MAKH FROM KHOA)) ORDER BY NEWID()

				SET @DEM3 = (SELECT COUNT(*) FROM dbo.BODE WHERE MAMH = @MAMH AND TRINHDO = @TRINHDO_THAP AND MAGV IN (SELECT MAGV FROM dbo.GIAOVIEN WHERE MAKH IN (SELECT MAKH FROM dbo.KHOA)))
				IF @DEM3 >= (@SOCAUTHI - @DEM1 - @DEM2) -- DU CAU THI
				BEGIN
					--RAISERROR('YES', 16, 1)
					--DA CO DEM1, DEM2, LAY VUA DU DEM3
					INSERT INTO #TAM SELECT TOP (@SOCAUTHI - @DEM1 - @DEM2) CAUHOI, MAMH, TRINHDO, NOIDUNG, A, B, C, D, DAP_AN, MAGV FROM dbo.BODE WHERE TRINHDO = @TRINHDO_THAP AND MAMH = @MAMH AND MAGV IN (SELECT MAGV FROM GIAOVIEN WHERE MAKH IN (SELECT MAKH FROM KHOA)) ORDER BY NEWID()
				END
				ELSE -- CAU TDB BEN CS1 CHUA DU, LAY THEM CAU TDB BEN CS2
				BEGIN
					--DA CO DEM1, DEM2, LAY HET DEM3
					INSERT INTO #TAM SELECT TOP (@DEM3) CAUHOI, MAMH, TRINHDO, NOIDUNG, A, B, C, D, DAP_AN, MAGV FROM dbo.BODE WHERE TRINHDO = @TRINHDO_THAP AND MAMH = @MAMH AND MAGV IN (SELECT MAGV FROM GIAOVIEN WHERE MAKH IN (SELECT MAKH FROM KHOA)) ORDER BY NEWID()

					SET @DEM4 = (SELECT COUNT(*) FROM dbo.BODE WHERE MAMH = @MAMH AND TRINHDO = @TRINHDO_THAP AND MAGV IN (SELECT MAGV FROM dbo.GIAOVIEN WHERE MAKH NOT IN (SELECT MAKH FROM dbo.KHOA)))
					IF @DEM4 >= (@SOCAUTHI - @DEM1 - @DEM2 - @DEM3) -- DU CAU THI
					BEGIN
						--RAISERROR('YES', 16, 1)
						--DA CO DEM1, DEM2, DEM3, LAY VUA DU DEM4
						INSERT INTO #TAM SELECT TOP (@SOCAUTHI - @DEM1 - @DEM2 - @DEM3) CAUHOI, MAMH, TRINHDO, NOIDUNG, A, B, C, D, DAP_AN, MAGV FROM dbo.BODE WHERE TRINHDO = @TRINHDO_THAP AND MAMH = @MAMH AND MAGV IN (SELECT MAGV FROM GIAOVIEN WHERE MAKH NOT IN (SELECT MAKH FROM KHOA)) ORDER BY NEWID()
					END
					ELSE -- KHONG DU CAU THI, BAO LOI
					BEGIN
						SET @ErorStr = N'Thiếu câu hỏi thi! Thiếu "'+ rtrim(convert(nvarchar(200),@SoCauThi - (@DEM1 + @DEM2 + @DEM3 + @DEM4))) +N'" câu hỏi, cần thêm câu hỏi vào trình độ hiện tại (hoặc thấp hơn 1 bậc)!' 
						RAISERROR(@ErorStr, 16, 1)
						RETURN
					END
				END
			END
			ELSE -- %CAU TDA (CS1 + CS2) < 70% => KHONG DU CAU THI, BAO LOI
			BEGIN
				SET @ErorStr = N'Thiếu câu hỏi thi! Thiếu "'+ rtrim(convert(nvarchar(200),FLOOR(@SoCauThi*0.7) - (@DEM1 + @DEM2))) +N'" câu hỏi cùng trình độ để đủ chỉ tiêu ít nhất 70 phần trăm câu hỏi cùng trình độ!' 
				RAISERROR(@ErorStr, 16, 1)
				RETURN
			END
		END
	END
	ELSE -- TRINH DO C
	BEGIN
		SET @DEM1 = (SELECT COUNT(*) FROM dbo.BODE WHERE MAMH = @MAMH AND TRINHDO = @TRINHDO AND MAGV IN (SELECT MAGV FROM dbo.GIAOVIEN WHERE MAKH IN (SELECT MAKH FROM dbo.KHOA)))
		IF @DEM1 >= @SOCAUTHI -- DU CAU THI
		BEGIN
			--RAISERROR('YES', 16, 1)
			--LAY VUA DU DEM1
			INSERT INTO #TAM SELECT TOP (@SOCAUTHI) CAUHOI, MAMH, TRINHDO, NOIDUNG, A, B, C, D, DAP_AN, MAGV FROM dbo.BODE  WHERE TRINHDO = @TRINHDO AND MAMH = @MAMH AND MAGV IN (SELECT MAGV FROM GIAOVIEN WHERE MAKH IN (SELECT MAKH FROM KHOA)) ORDER BY NEWID() 
		END
		ELSE  -- BEN CS1 CHUA DU CAU THI
		BEGIN
			--LAY HET DEM1
			INSERT INTO #TAM SELECT TOP (@DEM1) CAUHOI, MAMH, TRINHDO, NOIDUNG, A, B, C, D, DAP_AN, MAGV FROM dbo.BODE  WHERE TRINHDO = @TRINHDO AND MAMH = @MAMH AND MAGV IN (SELECT MAGV FROM GIAOVIEN WHERE MAKH IN (SELECT MAKH FROM KHOA)) ORDER BY NEWID() 

			SET @DEM2 = (SELECT COUNT(*) FROM dbo.BODE WHERE MAMH = @MAMH AND TRINHDO = @TRINHDO AND MAGV IN (SELECT MAGV FROM dbo.GIAOVIEN WHERE MAKH NOT IN (SELECT MAKH FROM dbo.KHOA)))
			IF @DEM2 >= @SOCAUTHI - @DEM1 -- BEN CS2 + CS1 DU CAU THI
			BEGIN
				--RAISERROR('YES', 16, 1)
				--DA CO DEM1, LAY VUA DU DEM2
				INSERT INTO #TAM SELECT TOP (@SOCAUTHI - @DEM1) CAUHOI, MAMH, TRINHDO, NOIDUNG, A, B, C, D, DAP_AN, MAGV FROM dbo.BODE  WHERE TRINHDO = @TRINHDO AND MAMH = @MAMH AND MAGV IN (SELECT MAGV FROM GIAOVIEN WHERE MAKH NOT IN (SELECT MAKH FROM KHOA)) ORDER BY NEWID() 
			END
			ELSE -- KHONG DU CAU THI, BAO LOI
			BEGIN
				SET @ErorStr = N'Thiếu câu hỏi thi! Thiếu "'+ rtrim(convert(nvarchar(200),@SoCauThi - (@DEM1 + @DEM2))) +N'" câu hỏi cùng trình độ !' 
				RAISERROR(@ErorStr, 16, 1)
				RETURN
			END
		END
	END

	SELECT * FROM #TAM ORDER BY NEWID() 
END
GO

