USE [TN_CSDLPT]
GO

/****** Object:  StoredProcedure [dbo].[SP_TrungTenLop]    Script Date: 12/16/2020 15:25:58 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SP_TrungTenLop]
	@TENLOP NVARCHAR(50)
AS
BEGIN
	IF EXISTS(SELECT TENLOP FROM  dbo.LOP WHERE TENLOP = @TENLOP)
	BEGIN
		RAISERROR ('Tên lớp đã tồn tại!',16,1)
		RETURN
	END
   	IF EXISTS(SELECT TENLOP FROM  LINK1.TN_CSDLPT.dbo.LOP WHERE TENLOP = @TENLOP)
	BEGIN
		RAISERROR ('Tên lớp đã tồn tại!',16,1)
		RETURN
	END	
END
GO

