USE [TN_CSDLPT]
GO

/****** Object:  StoredProcedure [dbo].[SP_TIMBD]    Script Date: 12/5/2020 11:49:32 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SP_TIMBD] (@MAMH CHAR(5), @MASV CHAR(8), @LAN SMALLINT, @NGAYTHI DATETIME)
AS
BEGIN
	SELECT IDBD FROM dbo.BANGDIEM WHERE MAMH = @MAMH AND MASV = @MASV AND LAN = @LAN AND NGAYTHI = @NGAYTHI
END
GO

