USE [TN_CSDLPT]
GO

/****** Object:  StoredProcedure [dbo].[SP_XemBangDiem]    Script Date: 12/15/2020 17:18:42 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SP_XemBangDiem]
	@MAMH NCHAR(5),
	@LAN SMALLINT,
	@MALOP NCHAR(8)
AS
BEGIN
	SELECT SINHVIEN.MASV, HO, TEN, DIEM
	FROM dbo.SINHVIEN JOIN dbo.BANGDIEM
	ON BANGDIEM.MASV = SINHVIEN.MASV
	WHERE BANGDIEM.MAMH = @MAMH AND BANGDIEM.LAN = @LAN AND SINHVIEN.MALOP = @MALOP
END

GO

